<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(AvsCurrentIOSTargetFramework)</TargetFramework>
    <SupportedOSPlatformVersion>$(AvsMinSupportedIOSVersion)</SupportedOSPlatformVersion>
    <ProvisioningType>manual</ProvisioningType>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SafeAreaDemo\SafeAreaDemo.csproj" />
  </ItemGroup>
</Project>
